### ISSUE TITLE
Under selling it?

### ISSUE THREAD

**Issue by ReliablyAwkward** [nmcarp99/Obsidian-Auto-Definition-Link#3]
Hello, I am attempting to utilize your plugin to achieve what seems to be a unicorn case usage, I have been scouring the universe for over a year now trying to arrive at the context of what I am referring to as "Predictive note placement"...The closest I have come is using zapier, Which forces a sending back and forth to chat GPT for categorization of raw notes on the fly, but in a perfect world this would be already baked into obsidian, and I am curious if I am in the right spot, if there's a way to configure your plug-in to achieve this?

I have a 2.5 million word vault I want to be able to just give my days worth of raw notes to, and inferring from the previously structured hierarchy that the vault represents, since it's all geared towards one project, it can extrapolate from the meaning per blurbs worth of notes where it would predict I would place it and why, And if I approve I can just simply allow it to place it in that particular file in whatever folder, etc.

I utilize speech to text and talk a lot therefore, just to go about this process on my own over the years has taken up eons of my life to do manually. I am admittedly not tech savvy and I checked out your pages information already, regarding the plug-in directly, But it just looks like I'm looking at a foreign languages all, curious If you find this to be a creative breath of fresh air?

-grazie

**Comment by nmcarp99** [comment]
Hi Grazie,

Unfortunately, this extension does not provide this functionality. The functionality of which you are describing would require a considerable amount of language processing to understand which portions of your daily note should go into which file.

As best I understand, you want an extension to read, process, understand, and separate information from a single file. This would require artificial understanding of all topics discussed in order to discern between what content should go where (a task best performed by something like Chat GPT).

This extension automatically links notes (already separated by content) so you don't have to create links between files.

In my note taking, I find it is easier to write related content within the same note while I am learning the information, switching to a new file (or simply a new header) when switching to a new topic.

If I misunderstood something, feel free to correct me.

Thanks,
Nolan

**Comment by nmcarp99** [comment]
Closed due to no response
